export default {
  locale: 'ru',
  messages: {
    headerTitle: 'Квартплата 1.0',
    headerMenuLogout: 'Выйти',

    // accounts
    accountsTitle: 'Лицевые счета',
    accountFieldAccountNumber: 'Лицевой счет',
    accountFieldDateOpen: 'Дата открытия',
    accountFieldDateClose: 'Дата закрытия',

    // owners
    ownersTitle: 'Собственники',
    ownerTitle: 'Собственник',

    // citizens
    citizensTitle: 'Люди',
    citizenFieldGenderType: 'Пол',
    citizenFieldFirstName: 'Имя',
    citizenFieldLastName: 'Фамилия',
    citizenFieldFatherName: 'Отчество',
    citizenFieldBirthday: 'Дата рождения',

    normsTitle: 'Нормативы',
    normsGroupsNormsTitle: 'Группы нормативов',

    // organizations
    dictionariesTitle: 'Справочники',
    organizationTitle: 'Организации',
    contractorTypeTitle: 'Типы контрагентов',
    contractorTypeFieldName: 'Тип контрагента',
    contractorTypeFieldNameShort: 'Тип контрагента кратко',
    contractorTitle: 'Контрагенты',
    contractorGroupGeneralInfo: 'Основные реквизиты',
    contractorGroupBankInfo: 'Банковские реквизиты',
    contractorFieldFullName: 'Полное наименование контрагента',
    contractorFieldName: 'Наименование контрагента',
    contractorFieldInn: 'ИНН',
    contractorFieldKpp: 'КПП',
    contractorFieldOgrn: 'ОГРН',
    contractorFieldMailingAddress: 'Почтовый адрес',
    contractorFieldLegalAddress: 'Юридический Адрес',
    contractorFieldPhone: 'Телефон',
    contractorFieldFax: 'Факс',
    contractorFieldEmail: 'Электронная почта',
    contractorFieldWebSite: 'Веб-сайт',
    contractorFieldBankName: 'Наименование банка',
    contractorFieldBankAddress: 'Адрес банка',
    contractorFieldSettlementAccount: 'Расчетный счет',
    contractorFieldCorrespondentAccount: 'Корреспондентский счет',
    contractorFieldBankIdentificationCode: 'БИК',

    // address
    addressTitle: 'Адресная часть',
    streetTypeTitle: 'Типы улиц',
    streetTypeFieldName: 'Тип улицы',
    streetTypeFieldNameShort: 'Тип улицы кратко',
    streetTitle: 'Улицы',
    streetFieldName: 'Улица',
    buildingTitle: 'Строения',
    buildingFieldHouse: 'Дом',
    buildingFieldHouseNumber: 'Номер дома',
    buildingFieldHousing: 'Корпус',
    apartmentTitle: 'Квартиры',
    apartmentFieldApartment: 'Квартира',
    apartmentFieldApartmentNumber: 'Номер',
    apartmentFieldApartmentLetter: 'Литера',
    apartmentFieldEntrance: 'Подъезд',
    apartmentFieldFloor: 'Этаж',
    apartmentFieldTotalArea: 'Общая площадь',
    apartmentFieldLivingArea: 'Жилая площадь',
    apartmentFieldRoomsNumber: 'Кол-во комнат',

    // services
    servicesTitle: 'Услуги',
    serviceTypeTitle: 'Типы услуг',
    serviceTypeFieldName: 'Тип услуги',
    serviceFieldName: 'Услуга',

    // tariffs
    tariffsTitle: 'Тарифы',
    tariffValuesTitle: 'Значения тарифа',
    tariffFieldName: 'Наименование тарифа',

    // constants
    constantsTitle: 'Константы',
    calculationTypeTitle: 'Виды расчета',
    calculationTypeFieldName: 'Вид расчета',
    calculationTypeFieldNameOrigin: 'Вид расчета (значение по умолчанию)',
    measurementUnitTitle: 'Единицы измерения',
    measurementUnitFieldName: 'Единица измерения',
    parameterTypeTitle: 'Виды параметров',
    parameterTypeFieldName: 'Параметр',
    parameterTypeFieldNameOrigin: 'Параметр (значение по умолчанию)',
    parameterTitle: 'Параметры',
    documentTypeTitle: 'Виды документов',
    documentTypeFieldName: 'Вид документа',
    genderTypeTitle: 'Виды пола',
    genderTypeFieldName: 'Пол',
    genderTypeFieldNameOrigin: 'Пол (значение по умолчанию)',
    registrationTypeTitle: 'Виды прописки',
    registrationTypeFieldName: 'Вид прописки',

    // documents
    documentsTitle: 'Документы',
    documentTitle: 'Документ',
    documentFieldSeries: 'Серия',
    documentFieldNumber: 'Номер',
    documentFieldIssuingAuthority: 'Кем выдан',
    documentFieldDateIssue: 'Дата выдачи',

    // commmon
    buttonAddNewRecord: 'Добавить новую запись',
    buttonAddNewParameter: 'Добавить новый параметр',
    buttonAddNewService: 'Добавить новую услугу',
    buttonAddNewValue: 'Добавить новое значение',
    buttonAddNewDocument: 'Добавить новый документ',
    buttonAddNewAttachment: 'Добавить вложение',
    buttonAddNewOwner: 'Добавить нового собственника',
    buttonFind: 'Найти',
    editPageCreateTitle: 'Создание новой записи',
    editPageEditTitle: 'Редактирование записи',
    confirmDelete: 'Подтвердите удаление записи.',
    buttonDelete: 'Удалить',
    buttonEdit: 'Редактировать',
    buttonSave: 'Сохранить',
    buttonAdd: 'Добавить',
    buttonCancel: 'Отмена',
    buttonView: 'Просмотр',
    buttonApply: 'Применить',
    buttonSelect: 'Выбрать',
    buttonChange: 'Изменить',
    tableColumnActions: 'Действия',
    fieldIsEmptyError: 'Поле не должно быть пустым!',
    getRequestErrorTitle: 'Ошибка сети',
    getRequestErrorDescription: 'Не удалось выполнить запрос на сервер.',
    getRequestErrorConflictDescription: 'Запрос не может быть выполнен из-за конфликтного обращения к ресурсу.',
    saveDataSuccessTitle: 'Сохранение',
    saveDataSuccessDescription: 'Данные успешно сохранены.',
    deleteRecordTitle: 'Удаление',
    deleteRecordSuccessDescription: 'Запись успешно удалена.',
    findPlaceholder: 'Начните вводить текст для поиска',
    findByStreetNamePlaceholder: 'Начните вводить название улицы для поиска',
    findByBuildingNamePlaceholder: 'Начните вводить номер дома для поиска',
    findByAccountNumberPlaceholder: 'Начните вводить номер лицевого счета для поиска',
    managementCompanyTitle: 'Управляющая компания',
    addressShortTitle: 'Адрес',
    commonFieldDateStart: 'Действует С',
    commonFieldDateEnd: 'Действует ПО',
    commonFieldValue: 'Значение',
    commonFieldCitizen: 'ФИО',
    filtersTitle: 'Фильтры',
    attachmentsTitle: 'Вложения',
    attachmentNameTitle: 'Название вложения',
    attachmentNamePlaceholder: 'Введите название вложения',
    addAttachmentFileSizeErrorTitle: 'Добавление вложения',
    addAttachmentFileSizeErrorDescription: 'Превышен максимальный размер файла (максимальный размер 15 мб.).',
    addAttachmentFileNameErrorTitle: 'Укажите наименование для вложений!',
    selectOwnerErrorTitle: 'Укажите собственника!',

    welcomePageTitle: 'Добро пожаловать',
    welcomePageText: 'Это альфа версия приложения, в данной версии реализован минимальный функционал.',
  },
};
