export default {
  locale: 'ru',
  messages: {
    headerTitle: 'Квартплата 1.0',
    headerMenuLogout: 'Выйти',

    dictionariesTitle: 'Справочники',
    organizationTitle: 'Организации',
    contractorTypeTitle: 'Типы контрагентов',
    contractorTypeFieldName: 'Тип контрагента',
    contractorTypeFieldNameShort: 'Тип контрагента кратко',
    contractorTitle: 'Контрагенты',
    contractorGroupGeneralInfo: 'Основные реквизиты',
    contractorGroupBankInfo: 'Банковские реквизиты',
    contractorFieldFullName: 'Полное наименование контрагента',
    contractorFieldName: 'Наименование контрагента',
    contractorFieldInn: 'ИНН',
    contractorFieldKpp: 'КПП',
    contractorFieldOgrn: 'ОГРН',
    contractorFieldMailingAddress: 'Почтовый адрес',
    contractorFieldLegalAddress: 'Юридический Адрес',
    contractorFieldPhone: 'Телефон',
    contractorFieldFax: 'Факс',
    contractorFieldEmail: 'Электронная почта',
    contractorFieldWebSite: 'Веб-сайт',
    contractorFieldBankName: 'Наименование банка',
    contractorFieldBankAddress: 'Адрес банка',
    contractorFieldSettlementAccount: 'Расчетный счет',
    contractorFieldCorrespondentAccount: 'Корреспондентский счет',
    contractorFieldBankIdentificationCode: 'БИК',

    addressTitle: 'Адресная часть',
    streetTypeTitle: 'Типы улиц',
    streetTypeFieldName: 'Тип улицы',
    streetTypeFieldNameShort: 'Тип улицы кратко',
    streetTitle: 'Улицы',
    streetFieldName: 'Улица',
    buildingTitle: 'Строения',
    buildingFieldHouse: 'Дом',
    buildingFieldHouseNumber: 'Номер дома',
    buildingFieldHousing: 'Корпус',
    apartmentTitle: 'Квартиры',
    apartmentFieldApartment: 'Квартира',
    apartmentFieldApartmentNumber: 'Номер',
    apartmentFieldApartmentLetter: 'Литера',
    apartmentFieldEntrance: 'Подъезд',
    apartmentFieldFloor: 'Этаж',
    apartmentFieldTotalArea: 'Общая площадь',
    apartmentFieldLivingArea: 'Жилая площадь',
    apartmentFieldRoomsNumber: 'Кол-во комнат',

    serviceTitle: 'Услуги',
    serviceTypeTitle: 'Типы услуг',
    serviceTypeFieldName: 'Тип услуги',
    serviceFieldName: 'Услуга',

    accountsTitle: 'Лицевые счета',
    normsTitle: 'Нормативы',
    normsGroupsNormsTitle: 'Группы нормативов',
    otherTitle: 'Прочее',
    otherTypePlateTitle: 'Типы плит',

    // commmon
    buttonAddNewRecord: 'Добавить новую запись',
    editPageCreateTitle: 'Создание новой записи',
    editPageEditTitle: 'Редактирование записи',
    confirmDelete: 'Подтвердите удаление записи.',
    buttonDelete: 'Удалить',
    buttonEdit: 'Редактировать',
    buttonSave: 'Сохранить',
    buttonCancel: 'Отмена',
    tableColumnActions: 'Действия',
    fieldIsEmptyError: 'Поле не должно быть пустым!',
    getRequestErrorTitle: 'Ошибка сети',
    getRequestErrorDescription: 'Не удалось выполнить запрос на сервер.',
    getRequestErrorConflictDescription: 'Запрос не может быть выполнен из-за конфликтного обращения к ресурсу.',
    saveDataSuccessTitle: 'Сохранение',
    saveDataSuccessDescription: 'Данные успешно сохранены.',
    deleteRecordTitle: 'Удаление',
    deleteRecordSuccessDescription: 'Запись успешно удалена.',
    findPlaceholder: 'Начните вводить текст для поиска',
    findByStreetNamePlaceholder: 'Начните вводить название улицы для поиска',
    findByBuildingNamePlaceholder: 'Начните вводить номер дома для поиска',

    welcomePageTitle: 'Добро пожаловать',
    welcomePageText: 'Это альфа версия приложения, в данной версии реализован минимальный функционал.',

    switchLanguage: 'Переключить язык:',
    messageCreateWidgetSendButton: 'Отправить',
    messageListHeader: 'Сообщения',
    sendingMessage: 'Отправка сообщения...',
    sendMessageFailed: 'Отправить сообщение не удалось.',
    gettingMessages: 'Получение сообщений...',
    getMessagesFailed: 'Получить сообщения не удалось.',
    linkMain: 'Главная',
    linkMessages: 'Сообщения',
  },
};
