export default {
  locale: 'ru',
  messages: {
    headerTitle: 'Квартплата 1.0',
    headerMenuLogout: 'Выйти',
    currentWorkingPeriodTitle: 'Текущий рабочий период: ',
    workingPeriodsTitle: 'Рабочие периоды',

    // accounts
    accountsTitle: 'Лицевые счета',
    accountFieldAccountNumber: 'Лицевой счет',
    accountFieldDateOpen: 'Дата открытия',
    accountFieldDateClose: 'Дата закрытия',
    buttonCreateAccount: 'Создать новый лицевой счет',
    editPageCreateAccountTitle: 'Создание лицевого счета',
    editPageEditAccountTitle: 'Редактирование лицевого счета',
    accountCardTitle: 'Карточка лицевого счета',

    calculationsTitle: 'Расчеты',
    openingBalanceTitle: 'Сальдо входящее',
    closingBalanceTitle: 'Сальдо текущее',
    consumptionTitle: 'Потребление',
    accrualTitle: 'Начисление',
    recalculationTitle: 'Перерасчет',
    paymentTitle: 'Оплата',

    // owners
    ownersTitle: 'Собственники',
    ownerTitle: 'Собственник',
    editPageAddOwnerOnAccountTitle: 'Добавление собственника на лицевой счет',
    editPageEditOwnerOnAccountTitle: 'Редактирование собственника на лицевом счете',

    // registered
    registeredTitle: 'Прописанные',
    registeredOneTitle: 'Прописанный',
    editPageAddRegisteredOnAccountTitle: 'Добавление прописанного на лицевой счет',
    editPageEditRegisteredOnAccountTitle: 'Редактирование прописанного на лицевом счете',

    // citizens
    citizensTitle: 'Люди',
    citizenFieldGenderType: 'Пол',
    citizenFieldFirstName: 'Имя',
    citizenFieldLastName: 'Фамилия',
    citizenFieldFatherName: 'Отчество',
    citizenFieldBirthday: 'Дата рождения',
    buttonCreateCitizen: 'Создать нового человека',
    editPageCreateCitizenTitle: 'Создание человека',
    editPageEditCitizenTitle: 'Редактирование человека',

    // norms
    normsTitle: 'Нормативы',
    normValuesTitle: 'Значения норматива',
    normFieldName: 'Наименование норматива',
    buttonCreateNorm: 'Создать новый норматив',
    editPageCreateNormTitle: 'Создание норматива',
    editPageEditNormTitle: 'Редактирование норматива',
    editPageAddValueOnNormTitle: 'Добавление значения на норматив',
    editPageEditValueOnNormTitle: 'Редактирование значения на нормативе',

    // meters
    metersTitle: 'Приборы учета',
    meterValuesTitle: 'Показания',
    meterFieldName: 'Наименование',
    meterFieldSerialNumber: 'Серийный номер',
    meterFieldValue: 'Показание',
    meterFieldConsumption: 'Расход',
    meterFieldDateValue: 'Дата снятия',
    buttonCreateMeter: 'Создать новый прибора учета',
    editPageCreateMeterTitle: 'Создание прибора учета',
    editPageEditMeterTitle: 'Редактирование прибора учета',
    editPageAddMeterOnAccountTitle: 'Добавление прибора учета на лицевой счет',
    editPageEditMeterOnAccountTitle: 'Редактирование прибора учета на лицевом счете',
    editPageAddValueOnMeterTitle: 'Добавление показания на прибор учета',
    editPageEditValueOnMeterTitle: 'Редактирование показания на приборе учета',

    // organizations
    dictionariesTitle: 'Справочники',
    organizationTitle: 'Организации',
    contractorTypeTitle: 'Типы контрагентов',
    contractorTypeFieldName: 'Тип контрагента',
    contractorTypeFieldNameShort: 'Тип контрагента кратко',
    buttonCreateContractorType: 'Создать новый тип контрагента',
    editPageCreateContractorTypeTitle: 'Создание типа контрагента',
    editPageEditContractorTypeTitle: 'Редактирование типа контрагента',
    contractorTitle: 'Контрагенты',
    contractorGroupGeneralInfo: 'Основные реквизиты',
    contractorGroupBankInfo: 'Банковские реквизиты',
    contractorFieldFullName: 'Полное наименование контрагента',
    contractorFieldName: 'Наименование контрагента',
    contractorFieldInn: 'ИНН',
    contractorFieldKpp: 'КПП',
    contractorFieldOgrn: 'ОГРН',
    contractorFieldMailingAddress: 'Почтовый адрес',
    contractorFieldLegalAddress: 'Юридический Адрес',
    contractorFieldPhone: 'Телефон',
    contractorFieldFax: 'Факс',
    contractorFieldEmail: 'Электронная почта',
    contractorFieldWebSite: 'Веб-сайт',
    contractorFieldBankName: 'Наименование банка',
    contractorFieldBankAddress: 'Адрес банка',
    contractorFieldSettlementAccount: 'Расчетный счет',
    contractorFieldCorrespondentAccount: 'Корреспондентский счет',
    contractorFieldBankIdentificationCode: 'БИК',
    buttonCreateContractor: 'Создать нового контрагента',
    editPageCreateContractorTitle: 'Создание контрагента',
    editPageEditContractorTitle: 'Редактирование контрагента',

    // address
    addressTitle: 'Адресная часть',
    streetTypeTitle: 'Типы улиц',
    streetTypeFieldName: 'Тип улицы',
    streetTypeFieldNameShort: 'Тип улицы кратко',
    buttonCreateStreetType: 'Создать новый тип улицы',
    editPageCreateStreetTypeTitle: 'Создание типа улицы',
    editPageEditStreetTypeTitle: 'Редактирование типа улицы',
    streetTitle: 'Улицы',
    streetFieldName: 'Улица',
    buttonCreateStreet: 'Создать новую улицу',
    editPageCreateStreetTitle: 'Создание улицы',
    editPageEditStreetTitle: 'Редактирование улицы',
    buildingTitle: 'Строения',
    buildingFieldHouse: 'Дом',
    buildingFieldHouseNumber: 'Номер дома',
    buildingFieldHousing: 'Корпус',
    buttonCreateBuilding: 'Создать новое строение',
    editPageCreateBuildingTitle: 'Создание строения',
    editPageEditBuildingTitle: 'Редактирование строения',
    editPageAddMeterOnBuildingTitle: 'Добавление прибора учета на строение',
    editPageEditMeterOnBuildingTitle: 'Редактирование прибора учета на строении',
    apartmentTitle: 'Квартиры',
    apartmentFieldApartment: 'Квартира',
    apartmentFieldApartmentNumber: 'Номер',
    apartmentFieldApartmentLetter: 'Литера',
    apartmentFieldEntrance: 'Подъезд',
    apartmentFieldFloor: 'Этаж',
    apartmentFieldTotalArea: 'Общая площадь',
    apartmentFieldLivingArea: 'Жилая площадь',
    apartmentFieldRoomsNumber: 'Кол-во комнат',
    buttonCreateApartment: 'Создать новую квартиру',
    editPageCreateApartmentTitle: 'Создание квартиры',
    editPageEditApartmentTitle: 'Редактирование квартиры',

    // services
    serviceTypeTitle: 'Типы услуг',
    serviceTypeFieldName: 'Тип услуги',
    buttonCreateServiceType: 'Создать новый тип услуги',
    editPageCreateServiceTypeTitle: 'Создание типа услуги',
    editPageEditServiceTypeTitle: 'Редактирование типа услуги',
    servicesTitle: 'Услуги',
    serviceFieldName: 'Услуга',
    buttonCreateService: 'Создать новую услугу',
    editPageAddServiceOnAccountTitle: 'Добавление услуги на лицевой счет',
    editPageEditServiceOnAccountTitle: 'Редактирование услуги на лицевом счете',
    editPageCreateServiceTitle: 'Создание услуги',
    editPageEditServiceTitle: 'Редактирование услуги',

    // tariffs
    tariffsTitle: 'Тарифы',
    tariffTitle: 'Тариф',
    tariffValuesTitle: 'Значения тарифа',
    tariffFieldName: 'Наименование тарифа',
    buttonCreateTariff: 'Создать новый тариф',
    editPageCreateTariffTitle: 'Создание тарифа',
    editPageEditTariffTitle: 'Редактирование тарифа',
    editPageAddValueOnTariffTitle: 'Добавление значения на тириф',
    editPageEditValueOnTariffTitle: 'Редактирование значения на тирифе',

    // constants
    constantsTitle: 'Константы',
    calculationTypeTitle: 'Виды расчета',
    calculationTypeFieldName: 'Вид расчета',
    calculationTypeFieldNameOrigin: 'Вид расчета (значение по умолчанию)',
    editPageEditCalculationTypeTitle: 'Редактирование вида расчета',
    measurementUnitTitle: 'Единицы измерения',
    measurementUnitFieldName: 'Единица измерения',
    measurementUnitShortTitle: 'Ед. изм.',
    buttonCreateMeasurementUnit: 'Создать новую единицу измерения',
    editPageCreateMeasurementUnitTitle: 'Создание единицы измерения',
    editPageEditMeasurementUnitTitle: 'Редактирование единицы измерения',
    parameterTypeTitle: 'Виды параметров',
    parameterTypeFieldName: 'Параметр',
    parameterTypeFieldNameOrigin: 'Параметр (значение по умолчанию)',
    editPageAddParameterTypeOnAccountTitle: 'Добавление параметра на лицевой счет',
    editPageEditParameterTypeOnAccountTitle: 'Редактирование параметра на лицевом счете',
    editPageEditParameterTypeTitle: 'Редактирование вида параметра',
    parameterTitle: 'Параметры',
    documentTypeTitle: 'Виды документов',
    documentTypeFieldName: 'Вид документа',
    buttonCreateDocumentType: 'Создать новый вид документа',
    editPageCreateDocumentTypeTitle: 'Создание вида документа',
    editPageEditDocumentTypeTitle: 'Редактирование вида документа',
    genderTypeTitle: 'Виды пола',
    genderTypeFieldName: 'Пол',
    genderTypeFieldNameOrigin: 'Пол (значение по умолчанию)',
    editPageEditGenderypeTitle: 'Редактирование вида пола',
    registrationTypeTitle: 'Виды прописки',
    registrationTypeFieldName: 'Вид прописки',
    buttonCreateRegistrationType: 'Создать новый вид прописки',
    editPageCreateRegistrationTypeTitle: 'Создание вида прописки',
    editPageEditRegistrationTypeTitle: 'Редактирование вида прописки',
    meterTypeTitle: 'Виды приборов учета',
    meterTypeFieldName: 'Вид прибора учета',
    meterTypeFieldNameOrigin: 'Вид прибора учета (значение по умолчанию)',
    editPageEditMeterTypeTitle: 'Редактирование вида прибора учета',

    // documents
    documentsTitle: 'Документы',
    documentTitle: 'Документ',
    documentOwnershipTitle: 'Документ права собственности',
    documentCitizenTitle: 'Документ человека',
    documentFieldSeries: 'Серия',
    documentFieldNumber: 'Номер',
    documentFieldIssuingAuthority: 'Кем выдан',
    documentFieldDateIssue: 'Дата выдачи',
    editPageAddDocumentOnCitizenTitle: 'Добавление документа на человека',
    editPageEditDocumentOnCitizenTitle: 'Редактирование документа на человеке',

    // commmon
    buttonAddNewRecord: 'Добавить новую запись',
    buttonAddNewParameter: 'Добавить новый параметр',
    buttonAddNewService: 'Добавить новую услугу',
    buttonAddNewValue: 'Добавить новое значение',
    buttonAddNewValueMeter: 'Добавить новое показание',
    buttonAddNewDocument: 'Добавить новый документ',
    buttonAddNewAttachment: 'Добавить вложение',
    buttonAddNewOwner: 'Добавить нового собственника',
    buttonAddNewRegistered: 'Добавить нового прописанного',
    buttonAddNewMeter: 'Добавить новый прибор учета',
    buttonFind: 'Найти',
    editPageCreateTitle: 'Создание новой записи',
    editPageEditTitle: 'Редактирование записи',
    confirmDelete: 'Подтвердите удаление записи.',
    buttonDelete: 'Удалить',
    buttonEdit: 'Редактировать',
    buttonSave: 'Сохранить',
    buttonAdd: 'Добавить',
    buttonCancel: 'Отмена',
    buttonView: 'Просмотр',
    buttonApply: 'Применить',
    buttonSelect: 'Выбрать',
    buttonChange: 'Изменить',
    buttonCard: 'Карточка',
    buttonGoToAccountList: 'Перейти к списку ЛС',
    tableColumnActions: 'Действия',
    fieldIsEmptyError: 'Поле не должно быть пустым!',
    getRequestErrorTitle: 'Ошибка сети',
    getRequestErrorDescription: 'Не удалось выполнить запрос на сервер.',
    getRequestErrorConflictDescription: 'Запрос не может быть выполнен из-за конфликтного обращения к ресурсу.',
    saveDataSuccessTitle: 'Сохранение',
    saveDataSuccessDescription: 'Данные успешно сохранены.',
    deleteRecordTitle: 'Удаление',
    deleteRecordSuccessDescription: 'Запись успешно удалена.',
    findPlaceholder: 'Начните вводить текст для поиска',
    managementCompanyTitle: 'Управляющая компания',
    addressShortTitle: 'Адрес',
    commonFieldDateStart: 'Действует С',
    commonFieldDateEnd: 'Действует ПО',
    commonFieldValue: 'Значение',
    commonFieldCitizen: 'ФИО',
    filtersTitle: 'Фильтры',
    attachmentsTitle: 'Вложения',
    attachmentNameTitle: 'Название вложения',
    attachmentNamePlaceholder: 'Введите название вложения',
    addAttachmentFileSizeErrorTitle: 'Добавление вложения',
    addAttachmentFileSizeErrorDescription: 'Превышен максимальный размер файла (максимальный размер 15 мб.).',
    addAttachmentFileNameErrorTitle: 'Укажите наименование для вложений!',
    selectOwnerErrorTitle: 'Укажите собственника!',
    selectRegisteredErrorTitle: 'Укажите прописанного!',
    selectMeterErrorTitle: 'Укажите прибор учета!',
    phoneNumbersTitle: 'Номера телефонов',
    registeredCountTitle: 'Кол-во прописанных',

    welcomePageTitle: 'Добро пожаловать',
    welcomePageText: 'Это альфа версия приложения, в данной версии реализован минимальный функционал.',
  },
};
